#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
# Set up a cluster according to the environment
# -----------------------------------------------------------------------------
# Load env vars from file `../aws/cloud.env`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/../.env

if [ ! -z "${1:-}" ] && [ ! "${1:-}" = "${CLOUD_PROVIDER}" ]
then
    $DIR/select $1
    source $DIR/../.env
fi

jq . << EOF
{
    "vendor": "${CLOUD_PROVIDER}",
    "region": "${CLUSTER_REGION}",
    "target": "${CLUSTER_TARGET}",
    "deploy": {
        "version": "${VERSION}",
        "project": "${PROJECT}",    
        "artifact": "${ARTIFACT}",
        "registry": "${REGISTRY}"
    }
}
EOF