#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
source .env

# Navigate to artifact source folder
pushd ./api > /dev/null

# Check for cloud-specific builds, otherwise use docker build
option=${1:-$CLOUD_PROVIDER}
case ${option:-} in
  azure)
    # Building images using the Azure Cloud
    az acr build -t ${IMAGE_ID} -r ${CLUSTER_TARGET} -f Dockerfile .
    ;;
  *)
    # Default: Build image using local docker
    docker build -t ${REGISTRY}/${IMAGE_ID} .
    ;;
esac