#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
source .env

clean() {
    target=$1
    
    # Delete the deployed helm chart (if exists)
    if helm history -n ${NAMESPACE} ${target} > /dev/null 2>&1
    then
        helm del ${target} -n ${NAMESPACE}
    fi
}

bootstrap() {
    DEPLOY_TARGET=${1:-}
    case ${DEPLOY_TARGET:-} in
        storage)
            clean "storage"
        ;;
        blue)
            # Remove the primary deployment
            clean "${DEPLOY_TARGET}-app"
        ;;
        green)
            # Remove the secondary deployment
            clean "${DEPLOY_TARGET}-app"
        ;;
        canary)
            # Remove the canary deployment
            clean "${DEPLOY_TARGET}-app"
        ;;
        *)
            # Default: Remove all known deployments (if they exist)
            clean "canary-app"
            clean "green-app"
            clean "blue-app"
            clean "storage"
        ;;
    esac
}

# Bootstrap the cleaning process
bootstrap $@

# Or you can remove the deployed resources manually
# kubectl delete service ${PROJECT} --wait
# kubectl delete deployment ${PROJECT} --wait
# kubectl get service
