# Default values for helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "demo"
replicaCount: 1

storage:
  name: demo-storage
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  class:
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    parameters: {}
  default: false
