#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
# Set up a cluster according to the environment
# -----------------------------------------------------------------------------
# Load env vars from file `../aws/cloud.env`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/../.env

jq . << EOF
{
    "vendor": "${CLOUD_PROVIDER}",
    "region": "${CLUSTER_REGION}",
    "target": "${CLUSTER_TARGET}",
    "deploy": {
        "version": "${VERSION}",
        "project": "${PROJECT}",    
        "artifact": "${ARTIFACT}",
        "registry": "${REGISTRY}"
    },
    "online": {
        "storage": null,
        "registry": null,
        "cluster": null,
        "hostname": null
    }
}
EOF